# Generated by Django 5.0.1 on 2024-02-16 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_information_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='years',
            field=models.ManyToManyField(blank=True, through='admissions.Mark', to='admissions.year'),
        ),
        migrations.AddField(
            model_name='mark',
            name='major',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admissions.major'),
        ),
        migrations.AddField(
            model_name='mark',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admissions.year'),
        ),
        migrations.AddField(
            model_name='year',
            name='majors',
            field=models.ManyToManyField(blank=True, through='admissions.Mark', to='admissions.major'),
        ),
    ]
