# Generated by Django 5.0.1 on 2024-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_mark_major_alter_mark_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAdviser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isCandidate',
            field=models.BooleanField(default=False),
        ),
    ]
