# Generated by Django 5.0.1 on 2024-02-20 09:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_comments_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='introduction',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='program',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
