# Generated by Django 5.0.1 on 2024-02-24 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
