# Generated by Django 5.0.1 on 2024-02-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_livestream_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestream',
            old_name='annouce',
            new_name='announce',
        ),
    ]
