# Generated by Django 5.0.1 on 2024-02-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_questions_beforelive_questions_duringlive'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default=None, upload_to='faculty/%Y/%m'),
        ),
    ]
