# Generated by Django 5.0.1 on 2024-02-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_faculty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='infosection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='admissions.informationsection'),
        ),
    ]
