# Generated by Django 5.0.1 on 2024-02-25 10:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0015_alter_information_infosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
