# Generated by Django 5.0.1 on 2024-02-25 11:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_information_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='livestream',
            name='questions',
        ),
        migrations.AddField(
            model_name='comments',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.information'),
        ),
        migrations.AddField(
            model_name='questions',
            name='livestream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.livestream'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 18, 30, 26, 887559)),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 18, 30, 26, 890704)),
        ),
    ]
